version: "3"

services:
  php-fpm:
    build:
      context: ./php
    container_name: "php-app1"

    volumes:
      - ../SuitesFlow:/var/www/
    networks:
      - app-network

  node-js:
    build:
      context: ../SuitesFlow-NodeJS
    container_name: "node-js"
    volumes:
      - ../SuitesFlow-NodeJS/:/usr/src/app/
      - node_modules:/usr/src/app/node_modules
      - nuxt:/usr/src/app/.nuxt

    working_dir: /usr/src/app/
    ports:
      - "3000:3000"
    command: sh -c "npm run dev"
    environment:
      - HOST=0.0.0.0
      - API_URL=http://localhost
      - SSR_API_URL=http://nginx-app1      
      - DATA_URL=http://localhost
      - SSR_DATA_URL=http://nginx-app1
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: "nginx-app1"

    volumes:
      - ../SuitesFlow:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
      - node-js

    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
  db:
    build:
      context: ./db
    container_name: "db-app1"
    environment:
      - MYSQL_DATABASE=render_appdb
      - MYSQL_USER=render_appdbu
      - MYSQL_PASSWORD=8BDGIegPW1
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./db/data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - 3306:3306
    depends_on:
      - php-fpm
    networks:
      - app-network

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "myadmin-app1"
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=localhost
    restart: always
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  node_modules:
  nuxt: